image: 'rust:latest'

stages:
    - build

build-rust-latest:
    stage: build
    script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo test --no-default-features --verbose

build-rust-nightly:
    stage: build
    image: rustlang/rust:nightly
    script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo test --no-default-features --verbose
