[package]
name = "nvector"
version = "0.1.0"
authors = ["Armin Becher <armin.becher@methodpark.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.3.1"

[[bench]]
name = "two_dim_array"
harness = false