[package]
name = "grid"
version = "0.1.0"
authors = ["Armin Becher <armin.becher@gmai.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3.1"
rand="0.7.3"

[[bench]]
name = "benches"
harness = false